#!/bin/sh
#  _____ _        _             _
# /  ___| |      | |           | |
# \ `--.| |_ __ _| |_ _   _ ___| |__   __ _ _ __
#  `--. | __/ _` | __| | | / __| '_ \ / _` | '__|
# /\__/ | || (_| | |_| |_| \__ | |_) | (_| | |
# \____/ \__\__,_|\__|\__,_|___|_.__/ \__,_|_|
#
# MODDWM STATUSBAR - Modular Dynamic Window Manager Statusbar.
# ----------------------------------------------------------------------------
#  "THE BEER-WARE LICENSE" (Revision 42):
#  Plasmoduck <plasmoduck@gmail.com> wrote this file.  As long as you retain this notice you
#  can do whatever you want with this stuff. If we meet some day, and you think
#  this stuff is worth it, you can buy me a beer in return - Plasmoduck.
# ---------------------------------------------------------------------------- 

playing () {
  mpc -h /usr/home/cjg/.mpd/socket | awk 'NR==1 {song = $0} NR==2 {if ($1 == "[playing]") p=1; sub(/.*\//, "")} END {printf("%s %s\n", p?"^c#83A598^ ^c#a89984^":"^c#D3869B^ ^c#a89984^", song)}' 
}

covid19 () {
	curl https://corona-stats.online/australia\?format\=json | python3 -c 'import sys,json;data=json.load(sys.stdin)["data"][0];print("^c#D3869B^^c#a89984^",data["cases"],"^c#D3869B^^c#a89984^",data["deaths"])'
sleep 60s
}

memory (){
	free | awk '(NR == 18) {print $6}'
}

cpu (){
    vmstat | awk 'NR==3 {print $(NF-2)}'
}

drive (){
	df -h | grep '/$' | awk '{print $5}'
}

cpu_temp (){
	sysctl dev.cpu.0.temperature | sed -e 's|.*: \([0-9]*\).*|\1|'
}

volume (){
	mixer -s vol | grep -Eo '[0-9]+$'
}

print_date (){
	date +"%H:%M"
}

weather() {
     LOCATION=Parramatta

     printf "%s" "$SEP1"
     if [ "$IDENTIFIER" = "unicode" ]; then
         printf "%s" "$(curl -s wttr.in/$LOCATION?format=1)"
     else
         printf "%s" "$(curl -s wttr.in/$LOCATION?format=1 | grep -o "[0-9].*")"
     fi
     printf "%s\n" "$SEP2"
     sleep 60s
}

while true
do
    xsetroot -name "^b#282828^^c#a89984^$(playing) ^c#FE8019^^c#FB4934^  ^c#a89984^$(cpu)% ^c#FE8019^^c#B8BB26^  ^c#a89984^$(memory) ^c#FE8019^^c#FABD2F^  ^c#a89984^$(drive) ^c#FE8019^^c#83A598^ ^c#a89984^ $(cpu_temp)°^c#FE8019^^c#D3869B^  ^c#a89984^$(volume)% ^c#FE8019^^c#8EC07C^  ^c#a89984^$(print_date) ^c#FE8019^"
	sleep 30s
done
