#!/bin/sh -e
#  _____ _        _             _
# /  ___| |      | |           | |
# \ `--.| |_ __ _| |_ _   _ ___| |__   __ _ _ __
#  `--. | __/ _` | __| | | / __| '_ \ / _` | '__|
# /\__/ | || (_| | |_| |_| \__ | |_) | (_| | |
# \____/ \__\__,_|\__|\__,_|___|_.__/ \__,_|_|
#
# MODDWM STATUSBAR - Modular Dynamic Window Manager Statusbar Wizard Flavour.
# ----------------------------------------------------------------------------
#  "THE BEER-WARE LICENSE" (Revision 42):
#  Plasmoduck <plasmoduck@gmail.com> wrote this file.  As long as you retain this notice you
#  can do whatever you want with this stuff. If we meet some day, and you think
#  this stuff is worth it, you can buy me a beer in return - Plasmoduck.
#  ---------------------------------------------------------------------------- 

playing () {
	mpc -h /usr/home/cjg/.mpd/socket | awk 'NR==1 {song = $0} NR==2 {if ($1 == "[playing]") p=1; sub(/.*\//, "")} END {printf("%s %s\n", p?"^c#7C9A8D^ ^c#a89984^":"^c#BF919D^ ^c#a89984^", song)}' 
}

memory (){
	free | awk '(NR == 18) {print $6}'
}

cpu (){	
	vmstat | awk 'NR==3 {print $(NF-2)}'
}

drive (){
	df -h | grep '/$' | awk '{print $5}'
}

cpu_temp (){
	sysctl dev.cpu.0.temperature | sed -e 's|.*: \([0-9]*\).*|\1|'
}

volume (){
	mixer -s vol | grep -Eo '[0-9]+$'
}

print_date (){
	date +"%H:%M"
}

while true
do
xsetroot -name "^b#2B2928^ ^c#a89984^$(playing) ^b#CC5E50^^c#a89984^  $(cpu)% ^b#A9AC43^^c#a89984^  $(memory) ^b#CBA650^^c#a89984^  $(drive) ^b#7C9A8D^^c#a89984^  $(volume)% ^b#BF919D^^c#FFFFFF^  $(print_date) "
	sleep 1
done
